- client/components/navbar.js
- client/routes.js
- client/store/user.js
- package-lock.json
- package.json
- server/auth/index.js
- server/db/db.js
- server/db/models/user.js
- server/index.js
> set up mongodb atlas

- server/db/db.js
- server/index.js
> mongo changes

- server/db/models/user.js
> user model defined

- server/db/models/user.js
> jobHistory added

- server/db/models/user.js
> Job History Array

- server/db/models/company.js
- server/db/models/companyJobHistory.js
- server/db/models/index.js
> Company model

- script/seed.js
- server/api/companies.js
- server/api/index.js
> added get routes

- server/api/users.js
- server/db/models/job.js
- server/db/models/user.js
> user routes defined

- server/db/models/user.js
> updated user model

- server/api/companies.js
> addded put route

- client/components/Jobs/AllJobs.js
- client/components/user-home.js
- client/store/index.js
- client/store/job.js
- server/api/companies.js
> react hook is working for alljob

- client/components/auth-form.js
- client/components/navbar.js
- package-lock.json
- package.json
- server/auth/index.js
- server/auth/linkedin.js
- server/db/models/user.js
> LinkedIn OAuth Working

- client/components/Companies/AllCompanies.js
- client/components/index.js
- client/components/user-home.js
- client/routes.js
- client/store/company.js
- client/store/index.js
- package-lock.json
- server/db/models/company.js
> added company component with working reducer

- script/seed.js
- server/db/models/company.js
- server/db/models/companyJobHistory.js
- server/db/models/job.js
- server/db/models/user.js
> Updated Models with References

- client/components/Jobs/AllJobs.js
- client/components/Jobs/UpdateJob.js
- script/seed.js
- server/db/models/job.js
- server/db/models/user.js
> seeding dummy

- script/seed.js
- server/db/models/company.js
> add. seeding data created

- client/components/Companies/AllCompanies.js
- script/seed.js
> changed AllCompanies to match jobs component format

- client/components/Users/AllUsers.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/users.js
- script/seed.js
> feature: all users component

- client/components/Jobs/AllJobs.js
- client/components/Jobs/SingleJob.js
- client/components/Jobs/UpdateJob.js
- client/routes.js
- client/store/job.js
- package-lock.json
- package.json
- server/api/jobs.js
- server/db/db.js
> working on update job

- client/components/Jobs/SingleJob.js
- client/components/Jobs/UpdateJob.js
- script/seed.js
- server/db/models/job.js
- server/db/models/user.js
> model changes

- client/components/Companies/AddCompany.js
- client/components/Companies/AddCompanyWValidation.js
- client/components/navbar.js
- client/routes.js
- client/store/company.js
- server/api/companies.js
> AddCompany component working

- client/components/Jobs/AppliedJobs.js
- client/components/Jobs/SavedJobs.js
- client/components/Users/SingleUser.js
- client/store/job.js
> working saved and applied jobs histroy

- client/components/navbar.js
- client/routes.js
- server/api/users.js
- server/middleware/index.js
> Some Admin/Employer Routes defined

- client/components/Jobs/ApplyJob.js
- client/components/Jobs/SingleJob.js
- client/components/navbar.js
- client/routes.js
- client/store/job.js
- package.json
- script/seed.js
- server/api/jobs.js
- server/api/users.js
- server/db/models/job.js
> apply job almost done

- server/db/db.js
> small mongo change

- .gitignore
- package-lock.json
- package.json
- server/db/db.js
- server/index.js
> Process-Env-Config

- package.json
> Heroku test

- server/db/db.js
> db-updated

- client/components/Companies/SingleCompany.js
- client/routes.js
> fixing updateCompmay

- client/components/Companies/SingleCompany.js
- client/components/Jobs/SingleJob.js
- client/components/Users/SingleUser.js
- client/routes.js
> feature: routes fixed

- client/components/Users/SingleUser.js
- client/routes.js
- server/api/users.js
> route-fixes

- server/auth/google.js
- server/db/models/user.js
> Google OAuth working

- client/components/Jobs/SingleJob.js
- client/routes.js
- server/api/jobs.js
- server/api/users.js
> Employer Applied View

- client/components/Companies/SingleCompany.js
- server/api/companies.js
> Company-Jobs

- client/components/Companies/AddCompany.js
- client/components/Companies/AllCompanies.js
- client/components/Companies/SingleCompany.js
- client/components/Companies/UpdateCompany.js
- client/components/Header.js
- client/components/Jobs/AddJob.js
- client/components/Jobs/AllJobs.js
- client/components/Jobs/UpdateJob.js
- client/components/Users/AllCandidates.js
- client/components/Users/AllEmployers.js
- client/components/Users/AllUsers.js
- client/components/Users/SingleUser.js
- client/components/user-home.js
- public/style.css
> created margins, cards for users, jobs fixed, inputs fixed

- client/components/Companies/SingleCompany.js
- client/components/Jobs/SingleJob.js
- client/components/SearchBar.js
- client/store/job.js
- script/seed.js
- server/api/jobs.js
- server/db/models/job.js
> feature: search functionality back-end done

- client/components/Chat/ChannelList.js
- client/components/Chat/MessageArea.js
- public/style.css
> chat box css

- client/components/Users/SingleUser.js
- client/components/Users/UpdateUser.js
- public/style.css
> css on user profile

- client/components/Companies/AllCompanies.js
- client/components/Jobs/AllJobs.js
- client/components/SimpleMenu.js
- client/components/navbar.js
- public/style.css
> changed allJobs css

- public/style.css
> sub navBar fix

- client/components/Companies/AddCompany.js
- client/components/Jobs/AddJob.js
- client/components/Jobs/AppliedJobs.js
- client/components/Jobs/SavedJobs.js
- client/components/Users/SingleUser.js
- client/components/Users/UpdateUser.js
- client/components/auth-form.js
- client/routes.js
- client/store/user.js
- public/style.css
- server/db/models/job.js
> Chatdesign

- client/components/Chat/ChannelList.js
- client/components/Chat/MessageArea.js
- client/components/Chat/MessageList.js
- client/components/Chat/NewChannel.js
- client/components/Chat/NewMessage.js
- client/components/Companies/SingleCompany.js
- client/components/Jobs/AllJobs.js
- client/components/Jobs/ApplyJobButton.js
- client/components/Jobs/SaveJobButton.js
- client/components/Users/AllCandidates.js
- client/components/Users/AllUsers.js
- client/store/company.js
- client/store/job.js
- client/store/user.js
- public/index.html
- public/style.css
- script/seed.js
- server/api/chat.js
- server/api/companies.js
- server/api/jobs.js
- server/api/users.js
- server/index.js
> cleaned up console.logs

- client/components/SearchResults.js
- server/api/jobs.js
> Search case-insensitive

- client/components/Users/UpdateUser.js
> Skills to UpDate User

- README.md
> Updated readME

- README.md
> added ss1.png to readme
